server:
  port: 3301
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://172.24.16.74/qyzx-group/qyzx-conf.git #配置文件所在仓库
          default-label: master #配置文件分支
          search-paths: conf  #配置文件所在根目录
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: 172.53.49.16:9092
    consumer:
      group-id: test
management:
  endpoints:
    web:
      exposure:
        include: "*"
# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: client
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug